site_name: robingame docs

theme:
  name: "readthedocs"

plugins:
  - search
  - mkdocstrings
  - mike

nav:
  - index.md
  - Quick start: quickstart.md
#  - tutorials.md
#  - How-To Guides: how-to-guides.md
  - Reference:
      - objects:
        - reference/objects/entity.md
        - reference/objects/group.md
        - reference/objects/game.md
      - text:
          - reference/text/font.md
      - image:
          - reference/image/sprite_animation.md
          - reference/image/utils.md
#  - explanation.md
